<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.0.37">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>431 Project A - Project A Data</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">431 Project A</span>
  </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html">Home</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./data.html" aria-current="page">Data</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./proposal.html">Proposal</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./analyses.html">Analyses</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./report.html">Final Report</a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-examples--tips" role="button" data-bs-toggle="dropdown" aria-expanded="false">Examples &amp; Tips</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-examples--tips">    
        <li>
    <a class="dropdown-item" href="./exampleA.html">
 <span class="dropdown-text">Project Proposal Example</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./exampleB.html">
 <span class="dropdown-text">Outline of Analysis Section</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./check_final.html">
 <span class="dropdown-text">Final Report Checklist</span></a>
  </li>  
    </ul>
  </li>
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="https://thomaselove.github.io/431-2022/contact.html">Contact Us</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://thomaselove.github.io/431-2022">431 Homepage</a>
  </li>  
</ul>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#what-data-will-i-use" id="toc-what-data-will-i-use" class="nav-link active" data-scroll-target="#what-data-will-i-use">What Data Will I Use?</a></li>
  <li><a href="#developing-the-data-overview" id="toc-developing-the-data-overview" class="nav-link" data-scroll-target="#developing-the-data-overview">Developing the Data: Overview</a></li>
  <li><a href="#data-development-task-instructions" id="toc-data-development-task-instructions" class="nav-link" data-scroll-target="#data-development-task-instructions">Data Development Task Instructions</a>
  <ul class="collapse">
  <li><a href="#task-1.-ingest-the-raw-data-into-chr_2022_raw" id="toc-task-1.-ingest-the-raw-data-into-chr_2022_raw" class="nav-link" data-scroll-target="#task-1.-ingest-the-raw-data-into-chr_2022_raw">Task 1. Ingest the raw data into <code>chr_2022_raw</code></a></li>
  <li><a href="#task-2.-filter-your-data-to-the-counties-in-the-states-youve-chosen" id="toc-task-2.-filter-your-data-to-the-counties-in-the-states-youve-chosen" class="nav-link" data-scroll-target="#task-2.-filter-your-data-to-the-counties-in-the-states-youve-chosen">Task 2. Filter your data to the counties in the states you’ve chosen</a>
  <ul class="collapse">
  <li><a href="#states-you-are-permitted-to-select" id="toc-states-you-are-permitted-to-select" class="nav-link" data-scroll-target="#states-you-are-permitted-to-select">States You Are Permitted to Select</a></li>
  <li><a href="#additional-task-2-notes" id="toc-additional-task-2-notes" class="nav-link" data-scroll-target="#additional-task-2-notes">Additional Task 2 Notes</a></li>
  </ul></li>
  <li><a href="#task-3.-select-five-variables-add-four-required-ones-and-clean-up-chr_2022" id="toc-task-3.-select-five-variables-add-four-required-ones-and-clean-up-chr_2022" class="nav-link" data-scroll-target="#task-3.-select-five-variables-add-four-required-ones-and-clean-up-chr_2022">Task 3. Select five variables, add four required ones, and clean up <code>chr_2022</code></a>
  <ul class="collapse">
  <li><a href="#the-86-variables-you-must-select-5-from" id="toc-the-86-variables-you-must-select-5-from" class="nav-link" data-scroll-target="#the-86-variables-you-must-select-5-from">The 86 variables you must select 5 from</a></li>
  <li><a href="#some-important-notes" id="toc-some-important-notes" class="nav-link" data-scroll-target="#some-important-notes">Some important notes</a></li>
  </ul></li>
  <li><a href="#cleaning-your-variables" id="toc-cleaning-your-variables" class="nav-link" data-scroll-target="#cleaning-your-variables">Cleaning Your Variables</a>
  <ul class="collapse">
  <li><a href="#the-binary-category" id="toc-the-binary-category" class="nav-link" data-scroll-target="#the-binary-category">The Binary Category</a></li>
  <li><a href="#ratios-that-need-converting" id="toc-ratios-that-need-converting" class="nav-link" data-scroll-target="#ratios-that-need-converting">Ratios That Need Converting</a></li>
  <li><a href="#variables-that-should-be-rescaled" id="toc-variables-that-should-be-rescaled" class="nav-link" data-scroll-target="#variables-that-should-be-rescaled">Variables that should be rescaled</a></li>
  <li><a href="#variables-that-are-proportions-should-be-converted-to-percentages" id="toc-variables-that-are-proportions-should-be-converted-to-percentages" class="nav-link" data-scroll-target="#variables-that-are-proportions-should-be-converted-to-percentages">Variables that are Proportions should be converted to Percentages</a></li>
  <li><a href="#variables-that-should-be-ok-as-is" id="toc-variables-that-should-be-ok-as-is" class="nav-link" data-scroll-target="#variables-that-should-be-ok-as-is">Variables that should be OK as is</a></li>
  </ul></li>
  <li><a href="#task-4.-create-factors-for-two-of-the-five-variables-you-chose-in-task-2" id="toc-task-4.-create-factors-for-two-of-the-five-variables-you-chose-in-task-2" class="nav-link" data-scroll-target="#task-4.-create-factors-for-two-of-the-five-variables-you-chose-in-task-2">Task 4. Create factors for two of the five variables you chose in Task 2</a>
  <ul class="collapse">
  <li><a href="#notes" id="toc-notes" class="nav-link" data-scroll-target="#notes">Notes</a></li>
  </ul></li>
  <li><a href="#task-5.-save-and-share-the-final-chr_2022-tibble" id="toc-task-5.-save-and-share-the-final-chr_2022-tibble" class="nav-link" data-scroll-target="#task-5.-save-and-share-the-final-chr_2022-tibble">Task 5. Save and share the final <code>chr_2022</code> tibble</a>
  <ul class="collapse">
  <li><a href="#notes-1" id="toc-notes-1" class="nav-link" data-scroll-target="#notes-1">Notes</a></li>
  </ul></li>
  <li><a href="#task-6.-provide-a-codebook-for-your-tibble" id="toc-task-6.-provide-a-codebook-for-your-tibble" class="nav-link" data-scroll-target="#task-6.-provide-a-codebook-for-your-tibble">Task 6. <strong>Provide a Codebook for Your Tibble</strong></a>
  <ul class="collapse">
  <li><a href="#notes-2" id="toc-notes-2" class="nav-link" data-scroll-target="#notes-2">Notes</a></li>
  </ul></li>
  <li><a href="#task-7.-print-and-summarize-your-tibble" id="toc-task-7.-print-and-summarize-your-tibble" class="nav-link" data-scroll-target="#task-7.-print-and-summarize-your-tibble">Task 7. <strong>Print and Summarize Your Tibble</strong></a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Project A Data</h1>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header>

<p>Most Recent Update: 2022-09-12 00:12:41.</p>
<section id="what-data-will-i-use" class="level1">
<h1>What Data Will I Use?</h1>
<p>Your Project A will use the 2022 version of the analytic data from County Health Rankings (<strong>CHR</strong>). You have already seen some versions of these data in Labs 02 and 03, but you’ll create and clean a new data set of your own for Project A.</p>
<p>The data are gathered at <a href="https://www.countyhealthrankings.org/explore-health-rankings/rankings-data-documentation">the County Health Rankings Data &amp; Documentation site</a>.</p>
<ul>
<li>The key elements we’ll use are in the <a href="https://www.countyhealthrankings.org/explore-health-rankings/rankings-data-documentation">Rankings Data &amp; Documentation section</a>, specifically the National Data &amp; Documentation section site for the <strong>2022 County Health Rankings</strong>.
<ul>
<li>Do not use data from previous editions of the CHR, and do not use the trends data available on their website for this project.</li>
</ul></li>
</ul>
<p>Specifically, you’ll need three files:</p>
<ul>
<li><a href="https://www.countyhealthrankings.org/sites/default/files/media/document/analytic_data2022.csv">the 2022 CHR CSV Analytic Data</a> (a .csv file)</li>
<li><a href="https://www.countyhealthrankings.org/sites/default/files/media/document/2022%20Analytic%20Documentation.pdf">the 2022 CHR Analytic Data Documentation</a> file (PDF), and</li>
<li><a href="https://www.countyhealthrankings.org/sites/default/files/media/document/DataDictionary_2022.pdf">the 2022 Data Dictionary</a> (PDF)</li>
</ul>
<p>These files are also available in the <a href="https://github.com/THOMASELOVE/431-data/tree/main/projectA">data folder for Project A</a> on Github.</p>
<p>You’ll wind up selecting five measures, which you’ll also want to look up at <a href="https://www.countyhealthrankings.org/2022-measures">this CHR 2022 Measures link</a> for further details, including who created the measure, how it is measured, and when it was measured.</p>
</section>
<section id="developing-the-data-overview" class="level1">
<h1>Developing the Data: Overview</h1>
<p>Obtaining and cleaning your data takes a little while, but you can start right now. There are seven main tasks to complete. You will create a clean tibble containing 200-400 rows (counties) and eleven variables, and then present the data, a codebook and some brief summaries, by following the steps below. Detailed instructions follow this overview.</p>
<ol type="1">
<li>Ingest the data into a raw tibble in R called <code>chr_2022_raw</code>, carefully.</li>
<li>Select the states (3-5 plus Ohio) that you want to study, creating a new <code>chr_2022</code> tibble that contains only the counties from those states, carefully.</li>
<li>Select nine variables (4 we’ll specify and 5 more you’ll select), rename them in useful ways, clean up problems, and then save this smaller tibble as <code>chr_2022</code>.</li>
<li>Create new factors (categorical variables) from two of your 5 selected variables from the previous task, and add them to <code>chr_2022</code> so you now have 11 variables.</li>
<li>Save the resulting <code>chr_2022</code> tibble, and share it with us in your Proposal.</li>
<li>Create a codebook for your <code>chr_2022</code> tibble which briefly but sufficiently describes your selected variables and subjects (counties.)</li>
<li>Print your <code>chr_2022</code> tibble (to prove it is a tibble) and then provide a modest set of appropriate numerical summaries of each variable.</li>
</ol>
</section>
<section id="data-development-task-instructions" class="level1">
<h1>Data Development Task Instructions</h1>
<p>Here are some key additional details for each step of this process. - Please refer to Dr.&nbsp;Love’s materials in the rest of these Project A Instructions, particularly in the Examples &amp; Tips section for more help.</p>
<section id="task-1.-ingest-the-raw-data-into-chr_2022_raw" class="level2">
<h2 class="anchored" data-anchor-id="task-1.-ingest-the-raw-data-into-chr_2022_raw">Task 1. Ingest the raw data into <code>chr_2022_raw</code></h2>
<p>Begin an R Project just for Project A, and create an R Markdown file within that project where you will do your data development work. Working from a template, or from your own best understanding of what works well for you, start by loading the packages you’ll need, including the <code>tidyverse</code> and any other packages you plan to use.</p>
<p>You’ll use <code>read_csv()</code> to ingest your raw <code>.csv</code> file into R and call the resulting tibble <strong>chr_2022_raw</strong>. But as you do this, you’ll need to remove the top row from the .csv within your R code. You should probably look at the raw .csv in Excel or another spreadsheet system so that you know why we need to do this.</p>
<p>To accomplish this, use the <code>skip = 1</code> command within your <code>read_csv()</code>. Sample code follows:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>data_url <span class="ot">&lt;-</span> </span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>  <span class="st">"https://www.countyhealthrankings.org/sites/default/files/media/document/analytic_data2022.csv"</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>chr_2022_raw <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(data_url, <span class="at">skip =</span> <span class="dv">1</span>, <span class="at">show_col_types =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>You should at this point have a chr_2022_raw tibble with 3194 rows and 725 columns.</p>
<p>Finally, to complete Task 1, you should now write code to restrict the <code>chr_2022_raw</code> data to only include the <strong>3082</strong> rows which have “county_ranked” values of 1, since the other rows will not be used by us in this project.</p>
</section>
<section id="task-2.-filter-your-data-to-the-counties-in-the-states-youve-chosen" class="level2">
<h2 class="anchored" data-anchor-id="task-2.-filter-your-data-to-the-counties-in-the-states-youve-chosen">Task 2. Filter your data to the counties in the states you’ve chosen</h2>
<p>Now we’ll filter the <strong>chr_2022_raw</strong> data containing 3082 rows and 725 columns to a new tibble called <code>chr_2022</code> which contains the 200-400 rows (counties) you will actually study in your project. Each row you’ll keep should have a <code>county_ranked</code> value of 1, as we’ve ensured at the end of Task 1. To go from 3082 counties to our final sample, you will need to select 4-6 states, including Ohio.</p>
<p>Your selection must include:</p>
<ul>
<li>the 88 counties of Ohio, and</li>
<li>all of the counties in a subset of 3-5 additional states in the US</li>
</ul>
<p>The number of counties (which have <code>county_ranked</code> values of 1) associated with each state (specified using its two-letter postal abbreviation code) is listed below, for your convenience.</p>
<ul>
<li>Do not include any of the six “states” (District of Columbia, Connecticut, Delaware, Hawaii, New Hampshire and Rhode Island) with fewer than 12 counties.</li>
</ul>
<section id="states-you-are-permitted-to-select" class="level3">
<h3 class="anchored" data-anchor-id="states-you-are-permitted-to-select">States You Are Permitted to Select</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>chr_2022_raw <span class="sc">|&gt;</span> <span class="fu">count</span>(statecode, state) <span class="sc">|&gt;</span> <span class="fu">filter</span>(n <span class="sc">&gt;</span> <span class="dv">12</span>) <span class="sc">|&gt;</span> <span class="fu">print</span>(<span class="at">n =</span> <span class="dv">50</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<pre><code># A tibble: 45 × 3
   statecode state     n
   &lt;chr&gt;     &lt;chr&gt; &lt;int&gt;
 1 01        AL       67
 2 02        AK       24
 3 04        AZ       15
 4 05        AR       75
 5 06        CA       58
 6 08        CO       59
 7 12        FL       67
 8 13        GA      159
 9 16        ID       43
10 17        IL      102
11 18        IN       92
12 19        IA       99
13 20        KS      104
14 21        KY      120
15 22        LA       64
16 23        ME       16
17 24        MD       24
18 25        MA       14
19 26        MI       83
20 27        MN       87
21 28        MS       82
22 29        MO      115
23 30        MT       47
24 31        NE       79
25 32        NV       16
26 34        NJ       21
27 35        NM       32
28 36        NY       62
29 37        NC      100
30 38        ND       48
31 39        OH       88    ## note: must be selected
32 40        OK       77
33 41        OR       35
34 42        PA       67
35 45        SC       46
36 46        SD       61
37 47        TN       95
38 48        TX      244
39 49        UT       28
40 50        VT       14
41 51        VA      133
42 53        WA       39
43 54        WV       55
44 55        WI       72
45 56        WY       23</code></pre>
<p>So, including <code>OH</code>, you will need a total of 200-400 counties, from 4-6 states. For example,</p>
<ul>
<li>one possible combination would be the states of <code>TX</code> (244 counties), <code>AZ</code> (15 counties) and <code>NM</code> (32 counties) in addition to <code>OH</code> (88 counties), which would yield 379 counties in 4 states</li>
<li>another combination would be the states of <code>WA</code> (39 counties), <code>WI</code> (72 counties), <code>WV</code> (55 counties) and <code>WY</code> (23 counties) to join <code>OH</code> (88 counties) yielding 277 counties in 5 states</li>
<li>and yet another would be <code>PA</code> (67), <code>NY</code> (62), <code>NJ</code> (21), <code>MD</code> (24) and <code>VA</code> (133) in addition to <code>OH</code> (88) yielding 395 counties in 6 states</li>
</ul>
<p>After making your selection, and applying it, you should have a tibble called <code>chr_2022</code> which contains 200-400 rows, and 725 columns. In Task 3, we’ll cut down those columns.</p>
</section>
<section id="additional-task-2-notes" class="level3">
<h3 class="anchored" data-anchor-id="additional-task-2-notes">Additional Task 2 Notes</h3>
<ol type="1">
<li>Choose your subset of states with the knowledge in mind that some variables in the CHR data are not available for some counties, and that each state you select must have more than 12 counties.</li>
<li>You should have some reason for selecting the states that you do, and you will need to describe that reason in a complete sentence or two in your proposal and your final report.</li>
<li>Since we’ve studied five Midwest states (and 437 counties) in Lab 2, we want you to look at a minimum of one state not included in that list, so your final selection of states (besides Ohio) must include at least one state <strong>other than</strong> Indiana, Illinois, Michigan and Wisconsin.</li>
<li>Don’t forget to filter the rows at the end of Task 1 so that only those rows with <code>county_ranked</code> values of 1 are included. Otherwise, your counts won’t match those shown above, and you’ll have lots of problems.</li>
</ol>
</section>
</section>
<section id="task-3.-select-five-variables-add-four-required-ones-and-clean-up-chr_2022" class="level2">
<h2 class="anchored" data-anchor-id="task-3.-select-five-variables-add-four-required-ones-and-clean-up-chr_2022">Task 3. Select five variables, add four required ones, and clean up <code>chr_2022</code></h2>
<p>Next, you will identify variables from the your existing <code>chr_2022</code> tibble describing your selected sample of counties to include only nine variables (columns) instead of the 725 you should have at the start of Task 3. These nine variables must include:</p>
<ul>
<li>the five-digit fips code for the county, which will be a convenient ID variable, which is called <code>fipscode</code> in the raw data.</li>
<li>the name of the county, which will be useful for labeling and identifying the counties, and which is called <code>county</code> in the raw data.</li>
<li>the <code>state</code>, which will be a multi-categorical (with 4-6 categories) variable</li>
<li>the <code>county_ranked</code> variable, which tells us whether the row should be included in our data (all of the rows you include in your data should have <code>county_ranked == 1</code>)</li>
<li>followed by five variables you select from the 86 variables in the raw CHR data set that are listed as <code>vXXX_rawvalue</code> (note: to select the entire group of 86 variables, you might try <code>select(ends_with("rawvalue"))</code> as part of a pipe of the data.)</li>
</ul>
<section id="the-86-variables-you-must-select-5-from" class="level3">
<h3 class="anchored" data-anchor-id="the-86-variables-you-must-select-5-from">The 86 variables you must select 5 from</h3>
<p>The <a href="https://www.countyhealthrankings.org/sites/default/files/media/document/2022%20Analytic%20Documentation.pdf">2022 CHR Analytic Data Documentation</a> file (PDF), and the <a href="https://www.countyhealthrankings.org/sites/default/files/media/document/DataDictionary_2022.pdf">2022 Data Dictionary</a> file (also PDF) are crucial here, as those are the ones that explain what the available variables mean, and how they should be labeled.</p>
<p>You should look up each measure you wind up selecting to learn more about it at <a href="https://www.countyhealthrankings.org/2022-measures">this CHR 2022 Measures link</a>.</p>
<p>You must select your five variables from the 85 variables in the raw (.csv) data file listed below. We show them here in the order in which they appear in the raw file. The listing “v001” in this table actually refers to the variable named “<strong>v001_rawvalue</strong>”.</p>
<pre><code> [1] "v001" "v002" "v036" "v042" "v037" "v009" "v011" "v133" "v070" "v132"
[11] "v049" "v134" "v045" "v014" "v085" "v004" "v088" "v062" "v005" "v050"
[21] "v155" "v168" "v069" "v023" "v024" "v044" "v082" "v140" "v043" "v135"
[31] "v125" "v124" "v136" "v067" "v137" "v173" "v147" "v127" "v128" "v129"
[41] "v144" "v145" "v060" "v061" "v139" "v083" "v138" "v039" "v143" "v003"
[51] "v122" "v131" "v021" "v149" "v159" "v160" "v167" "v169" "v151" "v063"
[61] "v065" "v141" "v142" "v171" "v172" "v015" "v161" "v148" "v158" "v156"
[71] "v153" "v154" "v166" "v051" "v052" "v053" "v054" "v055" "v081" "v080"
[81] "v056" "v126" "v059" "v057" "v058"</code></pre>
<p>For example, <code>v001_rawvalue</code> shows the raw values for the premature death measure. If you select this variable, it is up to you to use the documentation in the two PDF files I have linked to, as well as the information on the County Health Rankings website, to get a reasonable understanding of what the variable measures, and how it was collected.</p>
</section>
<section id="some-important-notes" class="level3">
<h3 class="anchored" data-anchor-id="some-important-notes">Some important notes</h3>
<ol type="1">
<li><p>Be sure to read this entire Data page (especially the material on Cleaning Your Variables) before selecting your variables, so you are aware of some features of the data we disclose below.</p></li>
<li><p>The five variables you select must be five different variables selected from the 86 variables in the CHR data set that are listed as <code>vXXX_rawvalue</code>. Some of the variables in that set of 86 are better choices than others, based on the criteria in the next few notes.</p></li>
<li><p>Each of the variables you select should be of some actual interest to you on its own, in terms of either providing a health outcome of interest, or potentially providing useful information about a feature of the county that might relate to that health outcome. Your five selected quantitative variables, selected by you from the 79 available “raw value” CHR variables, will need be treated as follows:</p></li>
</ol>
<ul>
<li>variable 1 will be treated as quantitative, and as an outcome of interest</li>
<li>two others (variables 2 and 3) will also be treated as quantitative predictors of interest for variable 1</li>
<li>variable 4 will be categorized into 2 mutually exclusive and collectively exhaustive levels to create a binary categorical variable of interest in predicting variable 1 (this is a terrible idea in practical work.)
<ul>
<li>Note that exactly one of the variables in the data (<code>v124</code> about drinking water violations) is already a binary (1 = Yes, 0 = No) variable (all other variables are quantitative.) You are permitted to use <code>v124</code> as your variable 4, if you like. <code>v124</code> may not be used as anything other than variable 4 in your work.</li>
</ul></li>
<li>variable 5 will be categorized into 3-5 mutually exclusive and collectively exhaustive levels to create a multi-categorical variable of interest in predicting variable 1 (this is almost as bad as what we’ll do to variable 4 in practical work)</li>
<li>the <code>state</code> will serve as another multi-categorical (with 4-6 categories) predictor of variable 1, so this will also be part of your tibble</li>
</ul>
<ol start="4" type="1">
<li>Each of the five variables you select must have data for at least 75% of the counties in each state you plan to study. This is something you will have to check on, in R, and you’ll have to present the code, and demonstrate with complete English sentences that you’ve verified this to be true for each of your five selections.</li>
</ol>
<p>The variables listed below are those with more than 10% missing values across all 3082 ranked counties in the US. While you are welcome to use any of these variables, you may want to look elsewhere to avoid problems with the “minimum 75% complete data” requirement. (Note that variable <code>v170_rawvalue</code> was not listed above since it is missing for all counties in the data.)</p>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: center;">Variable</th>
<th style="text-align: center;">Description</th>
<th style="text-align: center;">% missing</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;"><code>v129_rawvalue</code></td>
<td style="text-align: center;">infant mortality</td>
<td style="text-align: center;">60.5</td>
</tr>
<tr class="even">
<td style="text-align: center;"><code>v149_rawvalue</code></td>
<td style="text-align: center;">disconnected youth</td>
<td style="text-align: center;">60.4</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><code>v015_rawvalue</code></td>
<td style="text-align: center;">homicides</td>
<td style="text-align: center;">57.0</td>
</tr>
<tr class="even">
<td style="text-align: center;"><code>v138_rawvalue</code></td>
<td style="text-align: center;">drug overdose deaths</td>
<td style="text-align: center;">41.7</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><code>v128_rawvalue</code></td>
<td style="text-align: center;">child mortality</td>
<td style="text-align: center;">38.9</td>
</tr>
<tr class="even">
<td style="text-align: center;"><code>v158_rawvalue</code></td>
<td style="text-align: center;">juvenile arrests</td>
<td style="text-align: center;">37.3</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><code>v141_rawvalue</code></td>
<td style="text-align: center;">residential segregation</td>
<td style="text-align: center;">32.6</td>
</tr>
<tr class="even">
<td style="text-align: center;"><code>v148_rawvalue</code></td>
<td style="text-align: center;">firearm fatalities</td>
<td style="text-align: center;">26.3</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><code>v161_rawvalue</code></td>
<td style="text-align: center;">suicides</td>
<td style="text-align: center;">21.1</td>
</tr>
<tr class="even">
<td style="text-align: center;"><code>v021_rawvalue</code></td>
<td style="text-align: center;">High School graduation</td>
<td style="text-align: center;">19.5</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><code>v173_rawvalue</code></td>
<td style="text-align: center;">COVID-19 age-adjusted mortality</td>
<td style="text-align: center;">16.8</td>
</tr>
<tr class="even">
<td style="text-align: center;"><code>v061_rawvalue</code></td>
<td style="text-align: center;">HIV prevalence</td>
<td style="text-align: center;">14.2</td>
</tr>
<tr class="odd">
<td style="text-align: center;"><code>v160_rawvalue</code></td>
<td style="text-align: center;">Math scores</td>
<td style="text-align: center;">12.8</td>
</tr>
<tr class="even">
<td style="text-align: center;"><code>v039_rawvalue</code></td>
<td style="text-align: center;">Motor vehicle crash deaths</td>
<td style="text-align: center;">12.7</td>
</tr>
</tbody>
</table>
<ol start="5" type="1">
<li><p>Note that the descriptions in the table above (and in the tables below) associated with each variable are available as the first (deleted) row in the .csv file, and are also specified in the <a href="https://www.countyhealthrankings.org/sites/default/files/media/document/2022%20Analytic%20Documentation.pdf">2022 CHR Analytic Data Documentation</a> file.</p></li>
<li><p>Across your complete set of 4-6 selected states, the raw versions of each of your five selected variables must have at least <strong>ten</strong> distinct non-missing values. Again, you’ll need to show R code to do this checking, and demonstrate with complete English sentences that you have checked this to be true.</p></li>
</ol>
</section>
</section>
<section id="cleaning-your-variables" class="level2">
<h2 class="anchored" data-anchor-id="cleaning-your-variables">Cleaning Your Variables</h2>
<p>Check your five variables on the lists below. You should find all five of your selected variables on the list somewhere.</p>
<ul>
<li>If you plan to use the variable as quantitative, do what is suggested below as part of your data development work, and use that version in your codebook.</li>
<li>If you plan to use the variable as a categorical predictor, we still suggest you make the appropriate change to the original quantitative version as indicated below.</li>
</ul>
<section id="the-binary-category" class="level3">
<h3 class="anchored" data-anchor-id="the-binary-category">The Binary Category</h3>
<p><code>v124</code> is about Drinking Water Violations, is the only binary (1 = Yes, 0 = No) variable in the data. (all other variables are quantitative.) You are permitted to use <code>v124</code> as your variable 4, if you like. <code>v124</code> may not be used as anything other than variable 4 in your work.</p>
</section>
<section id="ratios-that-need-converting" class="level3">
<h3 class="anchored" data-anchor-id="ratios-that-need-converting">Ratios That Need Converting</h3>
<p>These variables are specified as providers per population in the raw data file. You will want to take the reciprocal (1/raw value) to rescale the results in terms of population per provider, which should be much more interpretable.</p>
<ul>
<li>You’ll note that this rescaled ratio is also provided in the raw file if you want it, for example, for primary care physicians, <code>v004_rawvalue</code> is providers per population, but <code>v004_other_data_1</code> is the ratio of population (residents) per provider.</li>
<li>Note that after rescaling by taking the reciprocal, you may see some counties with infinite ratios, which should then be changed to missing values.</li>
</ul>
<table class="table">
<thead>
<tr class="header">
<th style="text-align: right;">Code</th>
<th style="text-align: left;">Variable Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">v004</td>
<td style="text-align: left;">Primary care physicians</td>
</tr>
<tr class="even">
<td style="text-align: right;">v062</td>
<td style="text-align: left;">Mental health providers</td>
</tr>
<tr class="odd">
<td style="text-align: right;">v088</td>
<td style="text-align: left;">Dentists</td>
</tr>
<tr class="even">
<td style="text-align: right;">v131</td>
<td style="text-align: left;">Other primary care providers (not recommended)</td>
</tr>
</tbody>
</table>
<ul>
<li>We don’t recommend using variable <code>v131</code> in Project A because of the large number of counties with very small numbers of these providers listed.</li>
</ul>
</section>
<section id="variables-that-should-be-rescaled" class="level3">
<h3 class="anchored" data-anchor-id="variables-that-should-be-rescaled">Variables that should be rescaled</h3>
<table class="table">
<colgroup>
<col style="width: 12%">
<col style="width: 37%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">Code</th>
<th style="text-align: left;">Variable Description</th>
<th style="text-align: left;">What to do?</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">v001</td>
<td style="text-align: left;">Premature death</td>
<td style="text-align: left;">Divide by 100 to represent losses per 1000 population</td>
</tr>
<tr class="even">
<td style="text-align: right;">v051</td>
<td style="text-align: left;">Population</td>
<td style="text-align: left;">Either use log10(population), or divide population by 1000 to represent population in thousands.</td>
</tr>
<tr class="odd">
<td style="text-align: right;">v061</td>
<td style="text-align: left;">HIV prevalence</td>
<td style="text-align: left;">Divide by 100 to represent cases per 1000 population (caution: substantial missing data)</td>
</tr>
<tr class="even">
<td style="text-align: right;">v063</td>
<td style="text-align: left;">Median household income</td>
<td style="text-align: left;">Divide by 1000 to represent in thousands of dollars</td>
</tr>
</tbody>
</table>
</section>
<section id="variables-that-are-proportions-should-be-converted-to-percentages" class="level3">
<h3 class="anchored" data-anchor-id="variables-that-are-proportions-should-be-converted-to-percentages">Variables that are Proportions should be converted to Percentages</h3>
<p>Each of the variables listed below are proportions (between 0 and 1). Before you use them in any analyses, please <strong>multiply them by 100</strong> in your data development (using mutate) to turn their values into percentages (between 0 and 100) and this will seriously ease the interpretation of slopes and transformations for these variables.</p>
<table class="table">
<colgroup>
<col style="width: 8%">
<col style="width: 91%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">Code</th>
<th style="text-align: left;">Variable Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">v002</td>
<td style="text-align: left;">Poor or fair health</td>
</tr>
<tr class="even">
<td style="text-align: right;">v003</td>
<td style="text-align: left;">Uninsured adults (pick v003 or v085, but not both)</td>
</tr>
<tr class="odd">
<td style="text-align: right;">v009</td>
<td style="text-align: left;">Adult smoking</td>
</tr>
<tr class="even">
<td style="text-align: right;">v011</td>
<td style="text-align: left;">Adult obesity</td>
</tr>
<tr class="odd">
<td style="text-align: right;">v021</td>
<td style="text-align: left;">High school graduation (pick v021 or v168, but not both, see note)</td>
</tr>
<tr class="even">
<td style="text-align: right;">v023</td>
<td style="text-align: left;">Unemployment</td>
</tr>
<tr class="odd">
<td style="text-align: right;">v024</td>
<td style="text-align: left;">Children in poverty</td>
</tr>
<tr class="even">
<td style="text-align: right;">v037</td>
<td style="text-align: left;">Low birthweight</td>
</tr>
<tr class="odd">
<td style="text-align: right;">v049</td>
<td style="text-align: left;">Excessive drinking</td>
</tr>
<tr class="even">
<td style="text-align: right;">v050</td>
<td style="text-align: left;">Mammography screening</td>
</tr>
<tr class="odd">
<td style="text-align: right;">v052</td>
<td style="text-align: left;">Proportion below 18 years of age</td>
</tr>
<tr class="even">
<td style="text-align: right;">v053</td>
<td style="text-align: left;">Proportion 65 and older</td>
</tr>
<tr class="odd">
<td style="text-align: right;">v054</td>
<td style="text-align: left;">Proportion Non-Hispanic Black (see note below)</td>
</tr>
<tr class="even">
<td style="text-align: right;">v055</td>
<td style="text-align: left;">Proportion American Indian and Alaska Native (see note below)</td>
</tr>
<tr class="odd">
<td style="text-align: right;">v056</td>
<td style="text-align: left;">Proportion Hispanic (see note below)</td>
</tr>
<tr class="even">
<td style="text-align: right;">v057</td>
<td style="text-align: left;">Proportion Females</td>
</tr>
<tr class="odd">
<td style="text-align: right;">v058</td>
<td style="text-align: left;">Proportion Rural</td>
</tr>
<tr class="even">
<td style="text-align: right;">v059</td>
<td style="text-align: left;">Proportion not proficient in English</td>
</tr>
<tr class="odd">
<td style="text-align: right;">v060</td>
<td style="text-align: left;">Diabetes prevalence</td>
</tr>
<tr class="even">
<td style="text-align: right;">v065</td>
<td style="text-align: left;">Children eligible for free or reduced price lunch</td>
</tr>
<tr class="odd">
<td style="text-align: right;">v067</td>
<td style="text-align: left;">Driving alone to work</td>
</tr>
<tr class="even">
<td style="text-align: right;">v069</td>
<td style="text-align: left;">Some college</td>
</tr>
<tr class="odd">
<td style="text-align: right;">v070</td>
<td style="text-align: left;">Physical inactivity</td>
</tr>
<tr class="even">
<td style="text-align: right;">v080</td>
<td style="text-align: left;">Proportion Native Hawaiian/Other Pacific Islander (see note below)</td>
</tr>
<tr class="odd">
<td style="text-align: right;">v081</td>
<td style="text-align: left;">Proportion Asian (see note below)</td>
</tr>
<tr class="even">
<td style="text-align: right;">v082</td>
<td style="text-align: left;">Children in single-parent households</td>
</tr>
<tr class="odd">
<td style="text-align: right;">v083</td>
<td style="text-align: left;">Limited access to healthy foods</td>
</tr>
<tr class="even">
<td style="text-align: right;">v085</td>
<td style="text-align: left;">Uninsured (pick v003 or v085, but not both)</td>
</tr>
<tr class="odd">
<td style="text-align: right;">v122</td>
<td style="text-align: left;">Uninsured children (pick v085 or v122, but not both)</td>
</tr>
<tr class="even">
<td style="text-align: right;">v126</td>
<td style="text-align: left;">Proportion Non-Hispanic White (see note below)</td>
</tr>
<tr class="odd">
<td style="text-align: right;">v132</td>
<td style="text-align: left;">Access to exercise opportunities</td>
</tr>
<tr class="even">
<td style="text-align: right;">v134</td>
<td style="text-align: left;">Proportion of driving deaths with alcohol involvement</td>
</tr>
<tr class="odd">
<td style="text-align: right;">v136</td>
<td style="text-align: left;">Severe housing problems</td>
</tr>
<tr class="even">
<td style="text-align: right;">v137</td>
<td style="text-align: left;">Long commute - driving alone</td>
</tr>
<tr class="odd">
<td style="text-align: right;">v139</td>
<td style="text-align: left;">Food insecurity</td>
</tr>
<tr class="even">
<td style="text-align: right;">v143</td>
<td style="text-align: left;">Insufficient sleep</td>
</tr>
<tr class="odd">
<td style="text-align: right;">v144</td>
<td style="text-align: left;">Frequent physical distress (pick v036 or v144, but not both)</td>
</tr>
<tr class="even">
<td style="text-align: right;">v145</td>
<td style="text-align: left;">Frequent mental distress (pick v042 or v145, but not both)</td>
</tr>
<tr class="odd">
<td style="text-align: right;">v149</td>
<td style="text-align: left;">Disconnected youth (caution: lots of missing data)</td>
</tr>
<tr class="even">
<td style="text-align: right;">v153</td>
<td style="text-align: left;">Homeownership</td>
</tr>
<tr class="odd">
<td style="text-align: right;">v154</td>
<td style="text-align: left;">Severe housing cost burden</td>
</tr>
<tr class="even">
<td style="text-align: right;">v155</td>
<td style="text-align: left;">Flu vaccinations</td>
</tr>
<tr class="odd">
<td style="text-align: right;">v166</td>
<td style="text-align: left;">Broadband access</td>
</tr>
<tr class="even">
<td style="text-align: right;">v168</td>
<td style="text-align: left;">High school completion (pick v021 or v168, but not both, see note)</td>
</tr>
<tr class="odd">
<td style="text-align: right;">v171</td>
<td style="text-align: left;">Childcare cost burden</td>
</tr>
</tbody>
</table>
<ul>
<li>If you are interested in studying race and ethnicity and their impact on a health outcome, these data aren’t particularly well suited to a detailed look. Instead we suggest using <code>v126</code> to incorporate this dimension as a predictor (or its inverse, 1 - <code>v126</code>), rather than including any of the other race/ethnicity variables, specifically <code>v053</code>, <code>v054</code>, <code>v055</code>, <code>v056</code>, <code>v080</code>, or <code>v081</code>. This is because there’s more variation in the <code>v126</code> data across the reported counties. Again, a serious look at the impact of race/ethnicity is beyond the scope of Project A.</li>
<li>Note that variable <code>v021</code> has more missing data than <code>v168</code>, should you be trying to choose between them.</li>
</ul>
</section>
<section id="variables-that-should-be-ok-as-is" class="level3">
<h3 class="anchored" data-anchor-id="variables-that-should-be-ok-as-is">Variables that should be OK as is</h3>
<p>The variables listed below should be fine as they are. Most of them are ratios, although a few are averages or indexes. The main issue for these variables is correctly specifying the units of measurement (note that the indexes don’t have units.)</p>
<table class="table">
<colgroup>
<col style="width: 8%">
<col style="width: 92%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: right;">Code</th>
<th style="text-align: left;">Variable Description</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">v005</td>
<td style="text-align: left;">Preventable hospital stays</td>
</tr>
<tr class="even">
<td style="text-align: right;">v014</td>
<td style="text-align: left;">Teen births</td>
</tr>
<tr class="odd">
<td style="text-align: right;">v015</td>
<td style="text-align: left;">Homicide rate (caution: lots of missing data)</td>
</tr>
<tr class="even">
<td style="text-align: right;">v036</td>
<td style="text-align: left;">Poor physical health days (pick v036 or v144, but not both)</td>
</tr>
<tr class="odd">
<td style="text-align: right;">v039</td>
<td style="text-align: left;">Motor vehicle crash deaths (caution: substantial missing data)</td>
</tr>
<tr class="even">
<td style="text-align: right;">v042</td>
<td style="text-align: left;">Poor mental health days (pick v042 or v145, but not both)</td>
</tr>
<tr class="odd">
<td style="text-align: right;">v043</td>
<td style="text-align: left;">Violent crime</td>
</tr>
<tr class="even">
<td style="text-align: right;">v044</td>
<td style="text-align: left;">Income inequality</td>
</tr>
<tr class="odd">
<td style="text-align: right;">v045</td>
<td style="text-align: left;">Sexually transmitted infections</td>
</tr>
<tr class="even">
<td style="text-align: right;">v125</td>
<td style="text-align: left;">Air pollution - particulate matter</td>
</tr>
<tr class="odd">
<td style="text-align: right;">v127</td>
<td style="text-align: left;">Premature age-adjusted mortality</td>
</tr>
<tr class="even">
<td style="text-align: right;">v128</td>
<td style="text-align: left;">Child mortality (caution: lots of missing data)</td>
</tr>
<tr class="odd">
<td style="text-align: right;">v129</td>
<td style="text-align: left;">Infant mortality (caution: lots of missing data)</td>
</tr>
<tr class="even">
<td style="text-align: right;">v133</td>
<td style="text-align: left;">Food environment index</td>
</tr>
<tr class="odd">
<td style="text-align: right;">v135</td>
<td style="text-align: left;">Injury deaths</td>
</tr>
<tr class="even">
<td style="text-align: right;">v138</td>
<td style="text-align: left;">Drug overdose deaths (caution: lots of missing data)</td>
</tr>
<tr class="odd">
<td style="text-align: right;">v140</td>
<td style="text-align: left;">Social associations</td>
</tr>
<tr class="even">
<td style="text-align: right;">v141</td>
<td style="text-align: left;">Residential segregation - Black/White (pick v141 or v142, see note)</td>
</tr>
<tr class="odd">
<td style="text-align: right;">v142</td>
<td style="text-align: left;">Residential segregation - non-White/White (pick v141 or v142, see note)</td>
</tr>
<tr class="even">
<td style="text-align: right;">v147</td>
<td style="text-align: left;">Life expectancy</td>
</tr>
<tr class="odd">
<td style="text-align: right;">v148</td>
<td style="text-align: left;">Firearm fatalities (caution: substantial missing data)</td>
</tr>
<tr class="even">
<td style="text-align: right;">v151</td>
<td style="text-align: left;">Gender pay gap</td>
</tr>
<tr class="odd">
<td style="text-align: right;">v156</td>
<td style="text-align: left;">Traffic volume</td>
</tr>
<tr class="even">
<td style="text-align: right;">v158</td>
<td style="text-align: left;">Juvenile arrests (caution: lots of missing data)</td>
</tr>
<tr class="odd">
<td style="text-align: right;">v159</td>
<td style="text-align: left;">Reading scores</td>
</tr>
<tr class="even">
<td style="text-align: right;">v160</td>
<td style="text-align: left;">Math scores (caution: substantial missing data)</td>
</tr>
<tr class="odd">
<td style="text-align: right;">v161</td>
<td style="text-align: left;">Suicides (caution: substantial missing data)</td>
</tr>
<tr class="even">
<td style="text-align: right;">v167</td>
<td style="text-align: left;">School segregation (index from 0-1 with no units of measurement)</td>
</tr>
<tr class="odd">
<td style="text-align: right;">v169</td>
<td style="text-align: left;">School funding adequacy (gap measured in dollars per pupil)</td>
</tr>
<tr class="even">
<td style="text-align: right;">v172</td>
<td style="text-align: left;">Childcare centers per 1000 population under 5 years old</td>
</tr>
<tr class="odd">
<td style="text-align: right;">v173</td>
<td style="text-align: left;">COVID-19 age-adjusted mortality (caution: substantial missing data)</td>
</tr>
</tbody>
</table>
<ul>
<li>Note that variable <code>v141</code> has more missing data than <code>v142</code>, should you be trying to choose between them.</li>
</ul>
</section>
</section>
<section id="task-4.-create-factors-for-two-of-the-five-variables-you-chose-in-task-2" class="level2">
<h2 class="anchored" data-anchor-id="task-4.-create-factors-for-two-of-the-five-variables-you-chose-in-task-2">Task 4. Create factors for two of the five variables you chose in Task 2</h2>
<p>Create new categorical variables (factors) based on two of your previously selected variables, and add them to your <strong>chr_2022</strong> tibble. You’ll also retain the original (quantitative) versions of those two variables, so your tibble will now have 11 variables.</p>
<p>As mentioned, you will need to provide code to categorize two of your variables. Specifically…</p>
<ul>
<li>variable 4 will be categorized into 2 mutually exclusive and collectively exhaustive levels to create a binary categorical variable of interest in predicting variable 1 (this is a terrible idea in practical work.)</li>
<li>variable 5 will be categorized into 3-5 mutually exclusive and collectively exhaustive levels to create a multi-categorical variable of interest in predicting variable 1 (this is almost as bad as what we’ll do to variable 4 in practical work.)</li>
</ul>
<section id="notes" class="level3">
<h3 class="anchored" data-anchor-id="notes">Notes</h3>
<ol type="1">
<li>You will need to verify that all levels (categories) in each of your categorical variables contain at least 10 counties. Using <code>tabyl</code> is a good approach to check that this is true.</li>
</ol>
</section>
</section>
<section id="task-5.-save-and-share-the-final-chr_2022-tibble" class="level2">
<h2 class="anchored" data-anchor-id="task-5.-save-and-share-the-final-chr_2022-tibble">Task 5. Save and share the final <code>chr_2022</code> tibble</h2>
<p>Your final <strong>chr_2022</strong> tibble will thus contain 200-400 rows (counties) and 11 variables. You’ll save this tibble as an R data set (.Rds file) and share that file with us as part of your proposal.</p>
<p>In your R Markdown file, you will need to present all code necessary to take the original .csv data file and wind up with your <code>chr_2022</code> tibble so that we can run that code and get the same results you do.</p>
<p>Your main data set for analysis then should be gathered into a tibble called <strong>chr_2022</strong> containing the following information in this order:</p>
<ul>
<li>the identifying variables for each county, specifically:
<ul>
<li><code>fipscode</code> = the five-digit fips code for the state and county,</li>
<li><code>county</code> = the name of the county</li>
<li><code>state</code> = the postal abbreviation code for the state</li>
</ul></li>
<li>the variable <code>county_ranked</code>, which must be 1 for all rows in your data</li>
<li>your three selected quantitative variables, one of which is your planned outcome</li>
<li>your binary categorical variable derived from your fourth selected variable</li>
<li>your multi-categorical variable derived from your fifth selected variable</li>
<li>the “original” quantitative versions of the two variables (4 and 5) that you later categorized (if you chose the drinking water violations variable for variable 4, then you don’t need to repeat it here.)</li>
</ul>
<p>All of these variables should be <strong>renamed</strong> (and also have <code>clean_names()</code> from the <code>janitor</code> package applied) so as to have descriptive and maximally helpful variable names.</p>
<ul>
<li>For example, if you have decided to use as a quantitative variable something like <code>v009_rawvalue</code>, which is about adult smoking, you should rename the variable <code>v009_rawvalue</code> to <strong>adult_smoking</strong> in your tibble.</li>
<li>If <code>v009_rawvalue</code> (about adult smoking) is to be one of your categorical variables, then you should include both the original quantitative value (renamed <code>adult_smoking_raw</code>) and your categorical variable that you’ll actually use in analyses, which should be named <code>adult_smoking_cat</code>.</li>
</ul>
<p><strong>Save the Tibble</strong>: You should provide code that saves your tibble as an R data set into your R Project, with the file name <strong>chr_2022_YOURNAME.Rds</strong>. If you like, you can store this <code>.Rds</code> file in a <code>data</code> subdirectory within your R Project.</p>
<section id="notes-1" class="level3">
<h3 class="anchored" data-anchor-id="notes-1">Notes</h3>
<ol type="1">
<li>After your cleaning is done, each row in your <code>chr_2022</code> tibble should contain all of the counties within the 4-6 states you are studying, and no other counties should be included in your tibble. All rows of your <code>chr_2022</code> tibble must display a <code>county_ranked</code> value of 1.</li>
<li>If data for some counties are missing in the raw data for one or more of your variables, then these data should be indicated as missing (using NA) in the tibble.</li>
<li>There is no need to set a seed in this process, as you are not doing anything that involves selecting a random sample.</li>
</ol>
</section>
</section>
<section id="task-6.-provide-a-codebook-for-your-tibble" class="level2">
<h2 class="anchored" data-anchor-id="task-6.-provide-a-codebook-for-your-tibble">Task 6. <strong>Provide a Codebook for Your Tibble</strong></h2>
<p>Next, you will provide a codebook as part of your R Markdown file (and HTML/PDF output) that specifies the name of each variable in your tibble and its definition. After you select your variables, use the <a href="https://www.countyhealthrankings.org/2022-measures">County Health Rankings website’s 2022 Measures list</a>, and in particular the linked information on that page for full descriptions, definitions and limitations of the variables you have selected.</p>
<section id="notes-2" class="level3">
<h3 class="anchored" data-anchor-id="notes-2">Notes</h3>
<ol type="1">
<li><p>Be sure to include a description for each of the 11 variables (4 required including <code>county_ranked</code> + 5 you select + 2 categorical versions you create) in your final tibble, not just the ones that you wind up using in your analyses.</p></li>
<li><p>Include a description of what the cut points are for the two categorical variables you create, and specify how those cut points were chosen.</p></li>
</ol>
</section>
</section>
<section id="task-7.-print-and-summarize-your-tibble" class="level2">
<h2 class="anchored" data-anchor-id="task-7.-print-and-summarize-your-tibble">Task 7. <strong>Print and Summarize Your Tibble</strong></h2>
<ol type="1">
<li><p><strong>Print the Tibble</strong>: You will then prove that your tibble is in fact a tibble and not just a data frame by listing it, so that the first 10 rows are printed, and the columns are appropriately labeled.</p></li>
<li><p><strong>Numerical Summaries</strong>: You will then demonstrate main numerical summaries from the tibble by running the following summaries.</p></li>
</ol>
<ul>
<li><code>Hmisc::describe</code> on the whole tibble (all 11 variables: which is what you’ll do for the proposal.)</li>
<li>Note that in the project report, there are two additional requirements.
<ul>
<li><code>mosaic::favstats</code> on each of your quantitative variables (so variables 1, 2, and 3 and the original versions of variables 4 and 5)</li>
<li><code>janitor::tabyl</code> on your categorical variables 4 and 5 as well as on <code>state</code>.</li>
</ul></li>
</ul>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
    var links = window.document.querySelectorAll('a:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
          // target, if specified
          link.setAttribute("target", "_blank");
          // default icon
          link.classList.add("external");
      }
    }
});
</script>
</div> <!-- /content -->



</body></html>